force-app/main/default/objects/Account/fields/NationalId__c.field-meta.xml
<CustomField>
    <fullName>NationalId__c</fullName>
    <externalId>true</externalId>
    <label>NationalId</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CreditLine__c.field-meta.xml
<CustomField>
    <fullName>CreditLine__c</fullName>
    <label>CreditLine</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/InterestRate__c.field-meta.xml
<CustomField>
    <fullName>InterestRate__c</fullName>
    <label>InterestRate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Products_NovaBank</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Products_NovaBank.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Visa Plata</fullName>
    </customValue>
    <customValue>
        <fullName>Visa Oro</fullName>
    </customValue>
    <customValue>
        <fullName>Visa Infinite</fullName>
    </customValue>
    <masterLabel>Products NovaBank</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OportunidadesGanadasAPI.cls
/**

* @description       : API REST para obtener oportunidades ganadas por cliente

* @author            : ChangeMeIn@UserSettingsUnder.SFDoc

* @group             : Integraciones

* @last modified on  : 04-15-2026

* @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc

**/

@RestResource(urlMapping='/v1/clientes/*/oportunidades-ganadas')

global with sharing class OportunidadesGanadasAPI {
 
    @HttpGet

    global static void getOportunidades() {

        RestRequest req = RestContext.request;

        RestResponse res = RestContext.response;
 
        // Definir el tipo de contenido como JSON

        res.addHeader('Content-Type', 'application/json');
 
        try {

            // 1. Extraer el clientId de la URL

            String requestURI = req.requestURI;

            String clientId = requestURI.substringBetween('clientes/', '/oportunidades-ganadas');
 
            // 2. Buscar la cuenta y sus oportunidades ganadas.

            // AÑADIDO: WITH SECURITY_ENFORCED para validar permisos CRUD/FLS

            List<Account> cuentas = [

                SELECT Id, Name, NationalId__c,

                       (SELECT Id, Amount, CreditLine__c, CloseDate, LeadSource, Owner.Name, Product__c, InterestRate__c

                        FROM Opportunities

                        WHERE StageName = 'Closed Won') 

                FROM Account

                WHERE NationalId__c = :clientId

                WITH SECURITY_ENFORCED

                LIMIT 1

            ];
 
            if (cuentas.isEmpty()) {

                res.statusCode = 404;

                res.responseBody = Blob.valueOf('{"error": "Cliente no encontrado"}');

                return;

            }
 
            Account cliente = cuentas[0];
 
            // 3. Construir la respuesta mapeando a nuestras clases Wrapper

            RespuestaJSON respuesta = new RespuestaJSON();

            respuesta.clientId = cliente.NationalId__c;

            respuesta.nombreCliente = cliente.Name;

            respuesta.oportunidadesGanadas = new List<OportunidadDetalle>();
 
            for (Opportunity opp : cliente.Opportunities) {

                OportunidadDetalle det = new OportunidadDetalle();

                det.oportunidadId = opp.Id;

                det.producto = opp.Product__c;

                det.montoAprobado = opp.Amount;

                det.lineaCredito = opp.CreditLine__c;

                det.tasaInteres = opp.InterestRate__c;

                det.fechaCierre = String.valueOf(opp.CloseDate);

                det.canalOrigen = opp.LeadSource;

                det.ejecutivo = opp.Owner.Name;
 
                respuesta.oportunidadesGanadas.add(det);

            }
 
            respuesta.totalOportunidades = respuesta.oportunidadesGanadas.size();
 
            // 4. Enviar respuesta exitosa

            res.statusCode = 200;

            res.responseBody = Blob.valueOf(JSON.serialize(respuesta));
 
        } catch (System.QueryException qe) {

            // Captura específica si falla el WITH SECURITY_ENFORCED por falta de permisos

            res.statusCode = 403;

            res.responseBody = Blob.valueOf('{"error": "El usuario de integración no tiene permisos para leer los campos solicitados."}');

        } catch (Exception e) {

            // Captura general

            res.statusCode = 500;

            res.responseBody = Blob.valueOf('{"error": "' + e.getMessage() + '"}');

        }

    }
 
    // --- CLASES WRAPPER PARA GENERAR LA ESTRUCTURA EXACTA DEL JSON ---

    global class RespuestaJSON {

        public String clientId;

        public String nombreCliente;

        public List<OportunidadDetalle> oportunidadesGanadas;

        public Integer totalOportunidades;

    }
 
    global class OportunidadDetalle {

        public String oportunidadId;

        public String producto;

        public Decimal montoAprobado;

        public Decimal lineaCredito;

        public Decimal tasaInteres;

        public String fechaCierre;

        public String canalOrigen;

        public String ejecutivo;

    }

}
 